### PR TITLE
Formalized Standards

### PR DESCRIPTION
**Pull request by XedinUnknown**
A more formal language has been used. Certain parts have been disambiguated. Some grammar corrected.

- [ ] Add the specific SemVer version that must be followed.

### CODE REVIEW

**Comment by XedinUnknown** [comment]
@mecha, I remember you recently having suggestions about the standards. Please feel free to document them here.

**Comment by mecha** [comment]
_**Note**: The topics listed below might not necessarily be PHP-related. It might be wise to have a generic coding standards page, independent of language._

## 1. Liskov Substitution Principle

There is currently no mention of the principle. My recommendation is to mention that every higher level of abstraction should not restrict the parameters formally, but may encourage stricter types. The implementation should not rely on the stricter type.

Constructors are not bound by the principle, since they are not actual methods. Furthermore, when creating a new instance, the type is known and hence the parameters are also known. In the event that instances are being spawned dynamically using some saved FQN, such as `new $fqn($params)`, an abstract **base** class can be declared with a constructor which documents and encourages its specific parameters' types and order.

## 2. Tell don't Ask

Another basic principle which simplifies code and encourages better SoC. In essence, an object `A` should **tell** an object B what to do, rather than asking object **B** for data and then performing computation on object **B**  from within object **A**. Global scope counts as an "object" in this description.

Objects and their interfaces should be written in a way such that they provide an API for the operations that they support. It also encourages logic to be written in a granular fashion within different methods, perhaps even within different classes thus encouraging dependency injection.

```php
/*
 * Demonstration of Ask pattern
 */
interface AskBank
{
    public function getBalance();
    public function getDailyLimit();
    public function getAmountWithdrawnToday();
    public function set($x);
}

$amount = 100; // to withdraw
$today = $bank->getAmountWidthdrawnToday();
$limit = $bank->getDailyLimit()

if (($limit - $today - $amount) > 0) {
    $newBalance = $bank->getBalance() - $amount;
    $bank->set($newBalance);
} else {
    echo 'Exceeded daily limit!';
}
```

```php
/**
 * Demonstration of Tell pattern.
 */
interface TellBank
{
    public function withdraw($x);
    public function deposit($x);
    public function getBalance();
}

$amount = 100; // to withdraw
try {
    $bank->withdraw($amount);
} catch (OverDailyLimitException $e) {
    echo 'Exceeded daily limit!';
}
```

## 3. Naming Convention

There is mention of the following conventions:

>-   `interface TranslationCapableInterface` declares `public function translate()`.
> -   `interface TranslatorInterface extends TranslationCapableInterface`.
> -   `abstract class AbstractTranslator` declares `protected function _translate()`.
> -   `class Translator extends AbstractTranslator implements TranslatorInterface`
        declares `public function translate()`, which uses `_translate()`.

But no mention of the `*Aware` naming convention, for something that has a `get*()`.

I also recommend mentioning that naming and documentation of entities should be based on what an entity _is_, not what it _can do_. This is semi-implied by the `*Capable` naming convention, since an object *is capable* of doing `x`, not *can* do `x`; same meaning with different description. The same can be observed with the `*Aware` convention. I recommend documenting it anyway, to avoid depending on readers having to deduce this.

## 4. Make Abstract Layer Optional

Sometimes (not "rare" or "occasionally") an abstract layer is not required. This can be most commonly observed when interfaces declare a simple API that objects can implement without requiring state and without the need to inherit common functionality.

_Example_:

```php
// Interface Layer
interface HasherInterface
{
    public function hash($value);
}

// Concrete Layer
class Md5Hasher implements HasherInterface
{
    public function hash($value)
    {
        return md5($value);
    }
}
```

This eliminates potentially useless layers of abstract classes that do not define any functionality, but merely add more internal contracts for implementations which serve no purpose. This was recently discussed with regards to [`dhii/i18n-abstract`]. The main point presented against this was the fact that the abstract classes declared abstract "factory" methods for creating exceptions.

Classes that extend such abstract classes would be bound to implement methods which [are not used anywhere][1] in the abstract class, binding the implementation to implementing those methods even if it does not require them.

I am personally against this and would prefer that if an abstract _layer_ (not package) exists, it ought to provide some common functionality. This does not mean that a _package_ cannot exist for other related constructs, such as exceptions. Rather, it means that the underlying hierarchy of a concrete implementation is not required to contain a pure abstract implementation, if it's not required.

## 5. Declaring Interfaces for Specific Exceptions

This is a pattern that we follow, so I recommend that it be documented. It would also be wise to document a naming convention for exception names. The convention I usually follow is "what the method failed to do" - the answer to which is the name of the exception. For instance: `FailedToReadFileException`, `CouldNotResolveIdException`, etc. This might require further discussion before documenting.

## 6. Helper and Trait Packages/Layers

Lately we've been making repositories for just traits; a fantastic idea. However, I've also seen @XedinUnknown open a couple of `dhii/*-helper-base` packages. 

Both of these types of packages are not documented. Furthermore, I myself lam not sure what the difference is. Perhaps all `*-trait` packages are `*-helper-base` packages and we've simply not agreed on a naming convention.

I anticipate further discussion on this topic.

----

` die; `

[1]: https://github.com/Dhii/i18n-abstract/blob/release/0.2/src/AbstractTranslator.php
[`dhii/i18n-abstract`]: https://github.com/Dhii/i18n-abstract/tree/release/0.2

**Comment by XedinUnknown** [comment]
Been shamelessly ignoring this, and I'm sorry. Will read and comment here.

> The topics listed below might not necessarily be PHP-related. It might be wise to have a generic coding standards page, independent of language.

Yes!

> There is currently no mention of these (SOLID) set of principles - which we follow and take very seriously.

Unbelievable, but true. Thumbs up for mentioning it.

**Comment by XedinUnknown** [comment]
Also, see [exception system improvements][].

[exception system improvements]: https://www.notion.so/xedinunknown/Exception-System-Improvements-3e2e023d303145a881e8e11cb336ce64

**Comment by XedinUnknown** [comment]
Merging for now. If something needs to be added later, will consider additional changes.

**Pull request merged**
